services:
  arc-fe:
    #build:
    #  context: ..
    #  dockerfile: monorepo/services/arc-fe/Dockerfile.dev
    #ports:
    #  - "80:4200"
    #environment:
    #  - NODE_ENV=development
    #volumes:
    #  - ../arc-fe:/usr/src/app
    volumes:
      - ../arc-fe/dist/arc-fe/browser:/usr/share/nginx/html
    ports:
      - "80:80"

  arc-be:
    ports:
      - "3000:3000"
      - "5678:5678"
    volumes:
      - ../arc-be:/app
    environment:
      - FLASK_ENV=development

  rabbitmq:
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    ports:
      - "6379:6379"
  
  arc-db:
    ports:
      - "5432:5432"

  tesseract:
    ports:
      - "8884:8884"
  
  vllm:
    ports:
      - "8000:8000"
