services:
  arc-fe:
    volumes:
      - ../arc-fe/dist/arc-fe/browser:/usr/share/nginx/html
    ports:
      - "80:80"

  arc-be:
    ports:
      - "3000:3000"
      - "5678:5678"
    volumes:
      - ../arc-be:/app
    environment:
      - FLASK_ENV=development

  arc-ai:
    volumes:
      - ../arc-ai:/app
    ports:
      - "8010:8010"
      - "5679:5679"

  rabbitmq:
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    ports:
      - "6379:6379"
  
  arc-db:
    ports:
      - "5432:5432"

  tesseract:
    ports:
      - "8884:8884"