services:
  arc-fe:
    container_name: "arc-fe"
    build:
      context: ./services/arc-fe
      args:
        VERSION: master
    environment:
      - NODE_ENV=production
    depends_on:
      - arc-be
    restart: unless-stopped

  arc-be:
    container_name: "arc-be"
    build:
      context: ./services/arc-be
      args:
        VERSION: master
    environment:
      - SECRET_KEY=my_very_strong_secret
    depends_on:
      - rabbitmq
      - redis      
    restart: unless-stopped

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: "rabbitmq"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest 

  redis:
    image: "redis:alpine"
    container_name: "redis"