# Use an official Node runtime as a parent image
FROM node:22

# Set the working directory
WORKDIR /usr/src/app

# Install Angular CLI globally
RUN npm install -g @angular/cli

COPY arc-fe/package*.json .

RUN npm install

# Expose port 4200
EXPOSE 4200

# Start the Angular application
CMD ["ng", "serve", "--host", "0.0.0.0", "--poll", "2000"]
